services:

  web:
    build:
      context: .
    image: clone_status:1.0.0
    command: gunicorn -w 3 -t 300 -b 0.0.0.0:5000 app:app
    environment:
      LETSENCRYPT_HOST: ${SERVICE_URL}
      VIRTUAL_HOST: ${SERVICE_URL}
      VIRTUAL_PORT: 5000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    restart: always
    networks:
      - vaporware
    expose:
      - "5000"
    ports:
      - '5000:5000'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:5000/flask-health-check || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  vaporware:
    external:
      name: vaporware
